name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "20"

      - name: Install dependencies
        run: yarn install

      - name: Build
        run: yarn build

      - name: Deploy to GitHub Pages
        env:
          GITHUB_TOKEN: ${{ secrets.GH_ACTIONS_TOKEN }}
        run: |
          git config --global user.email "sid12g@naver.com"
          git config --global user.name "sid12g"
          git fetch origin gh-pages:gh-pages  # 원격의 gh-pages 브랜치를 가져옵니다
          git checkout gh-pages
          mv dist/* ./
          git add .
          git commit -m "Deploy to GitHub Pages"
          git push origin gh-pages
