name: NodeJS with Webpack

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: yarn install

      - name: Build
        run: yarn build

      - name: Configure git
        run: |
          git config --global user.email "sid12g@naver.com"
          git config --global user.name "sid12g"

      - name: Deploy to GitHub Pages
        env:
          GITHUB_TOKEN: ${{ secrets.GH_ACTIONS_TOKEN }}
        run: |
          git remote remove origin
          git remote add origin https://x-access-token:${{ secrets.GH_ACTIONS_TOKEN }}@github.com/${{ github.repository }}.git
          git fetch origin
          git checkout -b gh-pages origin/gh-pages
          mkdir gh-pages
          rsync -av --delete dist/ gh-pages/
          cd gh-pages
          git add .
          git commit -m "Deploy to GitHub Pages"
          git push origin gh-pages
